=== sgbarreros/inv/library/phpreports/PHPReport.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT REPORT (TITLE?,DESC?,PATH?,BACKGROUND_COLOR?,BACKGROUND_IMAGE?,CSS*,SQL?,USER?,PASSWORD?,CONNECTION?,INTERFACE?,DATABASE?,NO_DATA_MSG?,NO_DATA_FUNC?,TEMP?,DEBUG?,FORM?,DOCUMENT?,PAGE,GROUPS?)>
<!ATTLIST REPORT MARGINWIDTH CDATA #IMPLIED>
<!ATTLIST REPORT MARGINHEIGHT CDATA #IMPLIED>
<!ATTLIST REPORT MAX_ROW_BUFFER CDATA #IMPLIED>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DESC (#PCDATA)> 
<!ELEMENT PATH (#PCDATA)> 
<!ELEMENT BACKGROUND_COLOR (#PCDATA)> 
<!ELEMENT BACKGROUND_IMAGE (#PCDATA)> 
<!ELEMENT CSS (#PCDATA)>
<!ATTLIST CSS MEDIA CDATA #IMPLIED>
<!ELEMENT SQL (#PCDATA)> 
<!ELEMENT USER (#PCDATA)> 
<!ELEMENT PASSWORD (#PCDATA)> 
<!ELEMENT CONNECTION (#PCDATA)> 
<!ELEMENT INTERFACE (#PCDATA)> 
<!ELEMENT DATABASE (#PCDATA)> 
<!ELEMENT NO_DATA_MSG (#PCDATA)> 
<!ELEMENT TEMP (#PCDATA)> 
<!ELEMENT DEBUG (#PCDATA)>
<!ELEMENT FORM (FORM_NAME?,FORM_METHOD?,FORM_ACTION?)>
<!ELEMENT FORM_NAME (#PCDATA)>
<!ELEMENT FORM_METHOD (#PCDATA)>
<!ELEMENT FORM_ACTION (#PCDATA)>
<!ELEMENT DOCUMENT (HEADER?,FOOTER?)>
<!ELEMENT HEADER (ROW*)>
<!ELEMENT FOOTER (ROW*)>
<!ELEMENT ROW (COL*,CMD*)>
<!ELEMENT CMD (#PCDATA)>
<!ELEMENT COL (#PCDATA|LINK|BOOKMARK|XHTML|IMG)*>
<!ATTLIST COL TYPE (REGULAR|EXPRESSION|RAW_EXPRESSION|FIELD) "REGULAR">
<!ATTLIST COL ONCLICK		  CDATA #IMPLIED>
<!ATTLIST COL ONMOUSEOVER	  CDATA #IMPLIED>
<!ATTLIST COL ONMOUSEOUT	  CDATA #IMPLIED>
<!ATTLIST COL NUMBERFORMAT   CDATA #IMPLIED>
<!ATTLIST COL NUMBERFORMATEX CDATA #IMPLIED>
<!ATTLIST COL CELLCLASS      CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSEVEN  CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSODD   CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSEXPRESSION CDATA #IMPLIED>
<!ATTLIST COL TEXTCLASS		  CDATA #IMPLIED>
<!ATTLIST COL ROWSPAN        CDATA #IMPLIED>
<!ATTLIST COL COLSPAN        CDATA #IMPLIED>
<!ATTLIST COL WIDTH          CDATA #IMPLIED>
<!ATTLIST COL HEIGHT         CDATA #IMPLIED>
<!ATTLIST COL ALIGN          CDATA #IMPLIED>
<!ATTLIST COL VALIGN         CDATA #IMPLIED>
<!ATTLIST COL SUPPRESS (TRUE|FALSE) "FALSE">
<!ELEMENT PAGE (HEADER?,FOOTER?)>
<!ATTLIST PAGE CLASS       CDATA #IMPLIED>
<!ATTLIST PAGE SIZE        CDATA #IMPLIED>
<!ATTLIST PAGE WIDTH       CDATA #IMPLIED>
<!ATTLIST PAGE HEIGHT      CDATA #IMPLIED>
<!ATTLIST PAGE CELLPADDING CDATA #IMPLIED>
<!ATTLIST PAGE CELLSPACING CDATA #IMPLIED>
<!ATTLIST PAGE BORDER      CDATA #IMPLIED>
<!ATTLIST PAGE ALIGN       CDATA #IMPLIED>
<!ELEMENT GROUPS (GROUP+)>
<!ELEMENT GROUP (HEADER?,FIELDS?,FOOTER?,GROUP*)>
<!ATTLIST GROUP NAME CDATA #REQUIRED>
<!ATTLIST GROUP EXPRESSION CDATA #IMPLIED>
<!ATTLIST GROUP PAGEBREAK (TRUE|FALSE) "FALSE">
<!ATTLIST GROUP REPRINT_HEADER_ON_PAGEBREAK (TRUE|FALSE) "FALSE">
<!ATTLIST GROUP RESET_SUPPRESS_ON_PAGEBREAK (TRUE|FALSE) "FALSE">
<!ELEMENT FIELDS (ROW?)>
<!ELEMENT LINK (IMG?)>
<!ATTLIST LINK TYPE   (STATIC|DYNAMIC|EXPRESSION) "STATIC">
<!ATTLIST LINK TARGET CDATA #IMPLIED>
<!ATTLIST LINK TITLE  CDATA #IMPLIED>
<!ELEMENT BOOKMARK (#PCDATA)>
<!ATTLIST BOOKMARK TYPE (STATIC|DYNAMIC|EXPRESSION) "STATIC">
<!ATTLIST BOOKMARK CELLCLASS CDATA #IMPLIED>
<!ATTLIST BOOKMARK TEXTCLASS CDATA #IMPLIED>
<!ELEMENT IMG (#PCDATA)>
<!ATTLIST IMG WIDTH CDATA #IMPLIED>
<!ATTLIST IMG HEIGHT CDATA #IMPLIED>
<!ATTLIST IMG BORDER CDATA #IMPLIED>
<!ATTLIST IMG ALT CDATA #IMPLIED>
<!ELEMENT XHTML ANY>

=== sgbarreros/inv/modules/reports/report_debtors_aging_total.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT NUMBERFORMATEX="2">
	<TITLE>Sales Report</TITLE>
   <BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
<!--   <CSS>phpreports.css</CSS> -->
   <PAGE BORDER="1" SIZE="25" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="500">
      <HEADER>
         <ROW>
            <COL COLSPAN="6" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Totals by Aging periods</COL>
	 </ROW>
	 <ROW>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Total</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Paid</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Owing</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Aging</COL>
         </ROW>
      </HEADER>		
      <FOOTER>
	<ROW>
            <COL ALIGN="LEFT" COLSPAN="5" CELLCLASS="PAGE_LAYER">Sum</COL>
	</ROW>
         <ROW>
            <COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("inv_total")</COL>
            <COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("inv_paid")</COL>
            <COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("inv_owing")</COL>
            <COL ALIGN="RIGHT" COLSPAN="5" CELLCLASS="PAGE_LAYER"></COL>
         </ROW>
      </FOOTER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="citygroup" >

			<FIELDS>
				<ROW>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_total</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_paid</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_owing</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">aging</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>
