=== sgbarreros/inv/library/phpreports/PHPReport.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT REPORT (TITLE?,DESC?,PATH?,BACKGROUND_COLOR?,BACKGROUND_IMAGE?,CSS*,SQL?,USER?,PASSWORD?,CONNECTION?,INTERFACE?,DATABASE?,NO_DATA_MSG?,NO_DATA_FUNC?,TEMP?,DEBUG?,FORM?,DOCUMENT?,PAGE,GROUPS?)>
<!ATTLIST REPORT MARGINWIDTH CDATA #IMPLIED>
<!ATTLIST REPORT MARGINHEIGHT CDATA #IMPLIED>
<!ATTLIST REPORT MAX_ROW_BUFFER CDATA #IMPLIED>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DESC (#PCDATA)> 
<!ELEMENT PATH (#PCDATA)> 
<!ELEMENT BACKGROUND_COLOR (#PCDATA)> 
<!ELEMENT BACKGROUND_IMAGE (#PCDATA)> 
<!ELEMENT CSS (#PCDATA)>
<!ATTLIST CSS MEDIA CDATA #IMPLIED>
<!ELEMENT SQL (#PCDATA)> 
<!ELEMENT USER (#PCDATA)> 
<!ELEMENT PASSWORD (#PCDATA)> 
<!ELEMENT CONNECTION (#PCDATA)> 
<!ELEMENT INTERFACE (#PCDATA)> 
<!ELEMENT DATABASE (#PCDATA)> 
<!ELEMENT NO_DATA_MSG (#PCDATA)> 
<!ELEMENT TEMP (#PCDATA)> 
<!ELEMENT DEBUG (#PCDATA)>
<!ELEMENT FORM (FORM_NAME?,FORM_METHOD?,FORM_ACTION?)>
<!ELEMENT FORM_NAME (#PCDATA)>
<!ELEMENT FORM_METHOD (#PCDATA)>
<!ELEMENT FORM_ACTION (#PCDATA)>
<!ELEMENT DOCUMENT (HEADER?,FOOTER?)>
<!ELEMENT HEADER (ROW*)>
<!ELEMENT FOOTER (ROW*)>
<!ELEMENT ROW (COL*,CMD*)>
<!ELEMENT CMD (#PCDATA)>
<!ELEMENT COL (#PCDATA|LINK|BOOKMARK|XHTML|IMG)*>
<!ATTLIST COL TYPE (REGULAR|EXPRESSION|RAW_EXPRESSION|FIELD) "REGULAR">
<!ATTLIST COL ONCLICK		  CDATA #IMPLIED>
<!ATTLIST COL ONMOUSEOVER	  CDATA #IMPLIED>
<!ATTLIST COL ONMOUSEOUT	  CDATA #IMPLIED>
<!ATTLIST COL NUMBERFORMAT   CDATA #IMPLIED>
<!ATTLIST COL NUMBERFORMATEX CDATA #IMPLIED>
<!ATTLIST COL CELLCLASS      CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSEVEN  CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSODD   CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSEXPRESSION CDATA #IMPLIED>
<!ATTLIST COL TEXTCLASS		  CDATA #IMPLIED>
<!ATTLIST COL ROWSPAN        CDATA #IMPLIED>
<!ATTLIST COL COLSPAN        CDATA #IMPLIED>
<!ATTLIST COL WIDTH          CDATA #IMPLIED>
<!ATTLIST COL HEIGHT         CDATA #IMPLIED>
<!ATTLIST COL ALIGN          CDATA #IMPLIED>
<!ATTLIST COL VALIGN         CDATA #IMPLIED>
<!ATTLIST COL SUPPRESS (TRUE|FALSE) "FALSE">
<!ELEMENT PAGE (HEADER?,FOOTER?)>
<!ATTLIST PAGE CLASS       CDATA #IMPLIED>
<!ATTLIST PAGE SIZE        CDATA #IMPLIED>
<!ATTLIST PAGE WIDTH       CDATA #IMPLIED>
<!ATTLIST PAGE HEIGHT      CDATA #IMPLIED>
<!ATTLIST PAGE CELLPADDING CDATA #IMPLIED>
<!ATTLIST PAGE CELLSPACING CDATA #IMPLIED>
<!ATTLIST PAGE BORDER      CDATA #IMPLIED>
<!ATTLIST PAGE ALIGN       CDATA #IMPLIED>
<!ELEMENT GROUPS (GROUP+)>
<!ELEMENT GROUP (HEADER?,FIELDS?,FOOTER?,GROUP*)>
<!ATTLIST GROUP NAME CDATA #REQUIRED>
<!ATTLIST GROUP EXPRESSION CDATA #IMPLIED>
<!ATTLIST GROUP PAGEBREAK (TRUE|FALSE) "FALSE">
<!ATTLIST GROUP REPRINT_HEADER_ON_PAGEBREAK (TRUE|FALSE) "FALSE">
<!ATTLIST GROUP RESET_SUPPRESS_ON_PAGEBREAK (TRUE|FALSE) "FALSE">
<!ELEMENT FIELDS (ROW?)>
<!ELEMENT LINK (IMG?)>
<!ATTLIST LINK TYPE   (STATIC|DYNAMIC|EXPRESSION) "STATIC">
<!ATTLIST LINK TARGET CDATA #IMPLIED>
<!ATTLIST LINK TITLE  CDATA #IMPLIED>
<!ELEMENT BOOKMARK (#PCDATA)>
<!ATTLIST BOOKMARK TYPE (STATIC|DYNAMIC|EXPRESSION) "STATIC">
<!ATTLIST BOOKMARK CELLCLASS CDATA #IMPLIED>
<!ATTLIST BOOKMARK TEXTCLASS CDATA #IMPLIED>
<!ELEMENT IMG (#PCDATA)>
<!ATTLIST IMG WIDTH CDATA #IMPLIED>
<!ATTLIST IMG HEIGHT CDATA #IMPLIED>
<!ATTLIST IMG BORDER CDATA #IMPLIED>
<!ATTLIST IMG ALT CDATA #IMPLIED>
<!ELEMENT XHTML ANY>

=== sgbarreros/inv/modules/reports/report_biller_by_customer.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT NUMBERFORMATEX="2">
<TITLE>Sales Report</TITLE>
<BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
<!-- <CSS>phpreports.css</CSS> -->

	<PAGE BORDER="1" SIZE="2500" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="700">
		<HEADER>
			<ROW>
				<COL COLSPAN="4" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Sales by Customer - Group by Customer - Total</COL>
			</ROW>
		</HEADER>
		<FOOTER>
			<ROW>
				<COL COLSPAN="3" ALIGN="RIGHT" CELLCLASS="PAGE_LAYER">Page Total</COL>
				<COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("SUM_TOTAL")</COL>
			</ROW>
		</FOOTER>
	</PAGE>
	<GROUPS>
		<GROUP NAME="billergroup" EXPRESSION="Biller">
			<HEADER>
				<ROW>
					<COL COLSPAN="4" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">"Biller Name: " . $this->getValue("Biller")</COL>
				</ROW>
				<ROW>
					<COL COLSPAN="2" CELLCLASS="PAGE_LAYER">Customer Name</COL>
					<COL CELLCLASS="PAGE_LAYER">Sales</COL>
				</ROW>
			</HEADER>
			<FOOTER>
				<ROW>
					<COL COLSPAN="3" ALIGN="RIGHT" CELLCLASS="GROUP_LAYER">Total</COL>
					<COL ALIGN="LEFT" CELLCLASS="GROUP_LAYER" TEXTCLASS="BOLD" NUMBERFORMATEX="2" TYPE="EXPRESSION">$this->getSum("SUM_TOTAL")</COL>
				</ROW>
			</FOOTER>
			<FIELDS>
				<ROW>
					<COL COLSPAN="2" TYPE="FIELD" CELLCLASS="GROUP_LAYER" >Customer</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER" NUMBERFORMATEX="2">SUM_TOTAL</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>

=== sgbarreros/inv/modules/reports/report_debtors_owing_by_customer.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd"> 
<REPORT NUMBERFORMATEX="2">
	<TITLE>Sales Report</TITLE>
   <BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
 <!--  <CSS>phpreports.css</CSS>  -->
   <PAGE BORDER="1" SIZE="2500" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="500">
      <HEADER>
         <ROW>
            <COL COLSPAN="5" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Debtors - Amount owing per Customer</COL>
         </ROW>
         <ROW>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">ID</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Customer</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Total</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Paid</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Owing</COL>
         </ROW>
      </HEADER>		
      <FOOTER>
         <ROW>
            <COL ALIGN="RIGHT" COLSPAN="4" CELLCLASS="PAGE_LAYER">Total Owing</COL>
            <COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("inv_owing")</COL>
         </ROW>
      </FOOTER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="citygroup" >

			<FIELDS>
				<ROW>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">cid</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">customer</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_total</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_paid</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_owing</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>

=== sgbarreros/inv/modules/reports/report_products_sold_by_customer.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT NUMBERFORMATEX="2">
<TITLE>Sales Report</TITLE>
<BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
<!-- <CSS>phpreports.css</CSS> -->

	<PAGE BORDER="1" SIZE="2500" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="500">

	<HEADER>

	<ROW>
<COL COLSPAN="4" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Products Sold - Group by Customer - Total</COL>
</ROW>
</HEADER>

	<FOOTER>

	<ROW>
<COL ALIGN="RIGHT" COLSPAN="3" CELLCLASS="PAGE_LAYER">page total</COL>
<COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("sum_quantity")</COL>
</ROW>
</FOOTER>
</PAGE>

	<GROUPS>

	<GROUP NAME="citygroup" EXPRESSION="name">

	<HEADER>

	<ROW>
<COL CELLCLASS="GROUP_LAYER">Customer Name</COL>
<COL CELLCLASS="GROUP_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION" COLSPAN="3">$this->getValue("name")</COL>
</ROW>

	<ROW>
<COL CELLCLASS="GROUP_LAYER">Description</COL>
<COL CELLCLASS="GROUP_LAYER">Quantity</COL>
</ROW>
</HEADER>

	<FOOTER>

	<ROW>
<COL ALIGN="RIGHT" COLSPAN="3" CELLCLASS="GROUP_LAYER">Total</COL>
<COL ALIGN="LEFT" CELLCLASS="GROUP_LAYER" TEXTCLASS="BOLD" NUMBERFORMATEX="2" TYPE="EXPRESSION">$this->getSum("sum_quantity")</COL>
</ROW>
</FOOTER>

	<FIELDS>

	<ROW>
<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER" >description</COL>
<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER" NUMBERFORMATEX="2">sum_quantity</COL>
</ROW>
</FIELDS>
</GROUP>
</GROUPS>
</REPORT>

=== sgbarreros/inv/modules/reports/report_sales_total.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT NUMBERFORMATEX="2">
	<TITLE>Sales Report</TITLE>
   <BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
<!--   <CSS>phpreports.css</CSS>  -->
   <PAGE BORDER="1" SIZE="2500" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="500">
      <HEADER>
         <ROW>
            <COL COLSPAN="5" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Sales in total</COL>
         </ROW>
      </HEADER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="citygroup" >

			<FIELDS>
				<ROW>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">total</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>

=== sgbarreros/inv/modules/reports/report_debtors_by_aging.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT NUMBERFORMATEX="2">
	<TITLE>Sales Report</TITLE>
   <BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
<!--   <CSS>phpreports.css</CSS> -->
   <PAGE BORDER="1" SIZE="2500" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="500">
      <HEADER>
         <ROW>
            <COL COLSPAN="9" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Debtor invoices ordered by aging</COL>
	 </ROW>
<!--
	 <ROW>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Invoice ID</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Biller</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Customer</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Total</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Paid</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Owing</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Date</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Age</COL>
            <COL COLSPAN="1" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Aging</COL>
         </ROW>
-->
      </HEADER>		
      <FOOTER>
         <ROW>
            <COL ALIGN="RIGHT" COLSPAN="8" CELLCLASS="PAGE_LAYER">Total Owed</COL>
            <COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("inv_owing")</COL>
         </ROW>
      </FOOTER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="Aginggroup" EXPRESSION="Aging">
         <HEADER>
            <ROW>
               <COL CELLCLASS="GROUP_LAYER">Aging:</COL>
               <COL CELLCLASS="GROUP_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION" COLSPAN="8">$this->getValue("Aging")</COL>
            </ROW>
            <ROW>
                                        <COL  CELLCLASS="GROUP_LAYER">id</COL>
                                        <COL  CELLCLASS="GROUP_LAYER">Biller</COL>
                                        <COL  CELLCLASS="GROUP_LAYER">Customer</COL>
                                        <COL  CELLCLASS="GROUP_LAYER">Total</COL>
                                        <COL  CELLCLASS="GROUP_LAYER">Paid</COL>
                                        <COL  CELLCLASS="GROUP_LAYER">Owing</COL>
                                        <COL  CELLCLASS="GROUP_LAYER">Date</COL>
                                        <COL  CELLCLASS="GROUP_LAYER">Age</COL>
                                        <COL  CELLCLASS="GROUP_LAYER">Aging</COL>

            </ROW>
         </HEADER>
         <FOOTER>
            <ROW>
               <COL ALIGN="RIGHT" COLSPAN="5" CELLCLASS="GROUP_LAYER">Sum</COL>
               <COL ALIGN="LEFT" CELLCLASS="GROUP_LAYER" TEXTCLASS="BOLD" NUMBERFORMATEX="2" TYPE="EXPRESSION">$this->getSum("inv_owing")</COL>
            </ROW>
         </FOOTER>


			<FIELDS>
				<ROW>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">id</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">biller</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">customer</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_total</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_paid</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">inv_owing</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">date</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">age</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">Aging</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>

=== sgbarreros/inv/modules/reports/report_biller_total.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT NUMBERFORMATEX="2">
	<TITLE>Sales Report by Biller</TITLE>
   <BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
   <CSS></CSS>
   <PAGE BORDER="1" SIZE="2500" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="500">
      <HEADER>
         <ROW>
            <COL COLSPAN="5" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Sales in total by Biller</COL>
         </ROW>
      </HEADER>		
      <FOOTER>
         <ROW>
            <COL ALIGN="RIGHT" COLSPAN="4" CELLCLASS="PAGE_LAYER">page total</COL>
            <COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("sum_total")</COL>
         </ROW>
      </FOOTER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="citygroup" >

			<FIELDS>
				<ROW>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">name</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">sum_total</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>

=== sgbarreros/inv/library/phpreports/notused/sales.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT MARGINWIDTH="5" MARGINHEIGHT="5">
   <TITLE>Sales Report</TITLE>
   <BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
	<CSS>sales.css</CSS>
	<SQL>select CITY,NAME,TYPE,ITEM,VALUE from sales order by CITY,NAME,TYPE,ITEM</SQL>
	<CONNECTION>localhost</CONNECTION>
	<INTERFACE>mysql</INTERFACE>
	<DATABASE>phpreports</DATABASE>
	<NO_DATA_MSG>No data was found, check your query</NO_DATA_MSG>
	<DOCUMENT>
		<FOOTER>
			<ROW>
				<COL COLSPAN="2" CELLCLASS="FOOTER" TEXTCLASS="BOLDRED" ALIGN="RIGHT">GRAND TOTAL</COL>
				<COL CELLCLASS="FOOTER" TEXTCLASS="BOLDRED" TYPE="EXPRESSION" ALIGN="RIGHT" NUMBERFORMATEX="2">$this->getSum("VALUE")</COL>
			</ROW>
		</FOOTER>
	</DOCUMENT>
   <PAGE BORDER="0" SIZE="30" CELLSPACING="0" CELLPADDING="3">
		<HEADER>
			<ROW>
				<COL CELLCLASS="HEADER" COLSPAN="3">
					<XHTML>
						<TABLE BORDER="0" CELLPADDING="2" CELLSPACING="0" WIDTH="100%">
							<TR>
								<TD CLASS="HEADER">
									<b>JOHN DOE ENTERPRISES</b>
								</TD>
								<TD ROWSPAN="2" CLASS="HEADER" style="background:#A0A0A0;color:#FFFFFF;" ALIGN="CENTER">
										powered by<br/><b>phpreports</b>
								</TD>
							</TR>
							<TR>
								<TD CLASS="HEADER">
									<b>SALES REPORT</b>
								</TD>
							</TR>
							<TR>
								<TD COLSPAN="3"><HR/></TD>
							</TR>
						</TABLE>
					</XHTML>
				</COL>
			</ROW>	
		</HEADER>
		<FOOTER>
			<ROW>
				<COL ALIGN="RIGHT" CELLCLASS="FOOTER" COLSPAN="2">page total</COL>
				<COL TYPE="EXPRESSION" CELLCLASS="FOOTER" TEXTCLASS="BOLD" ALIGN="RIGHT" NUMBERFORMATEX="2">$this->getSum("VALUE")</COL>
			</ROW>	
			<ROW>
				<COL ALIGN="RIGHT" COLSPAN="3" TYPE="EXPRESSION" CELLCLASS="FOOTER">"page number ".$this->getPageNum()</COL>
			</ROW>
		</FOOTER>
	</PAGE>
	<GROUPS>
		<GROUP NAME="city" EXPRESSION="CITY" REPRINT_HEADER_ON_PAGEBREAK="TRUE" PAGEBREAK="TRUE">
			<HEADER>
				<ROW>
					<COL ALIGN="RIGHT" CELLCLASS="HEADER" WIDTH="50"><LINK TYPE="STATIC" TARGET="_blank" TITLE="explain of what is a city">http://www.whatisacity.com</LINK>city:</COL>
					<COL TYPE="EXPRESSION" CELLCLASS="HEADER" TEXTCLASS="BOLD" COLSPAN="2"><BOOKMARK TYPE="EXPRESSION" CELLCLASS="CITY" TEXTCLASS="BOOKMARK_TEXT">$this->getValue("CITY")</BOOKMARK>$this->getValue("CITY")</COL>
				</ROW>
			</HEADER> 
			<FOOTER>
				<ROW>
					<COL COLSPAN="3" CELLCLASS="FOOTER"></COL>
				</ROW>
				<ROW>
					<COL ALIGN="RIGHT" TYPE="EXPRESSION" CELLCLASS="FOOTER" COLSPAN="2">"total of ".$this->getValue("CITY")</COL>
					<COL TYPE="EXPRESSION" CELLCLASS="FOOTER" TEXTCLASS="BOLD" ALIGN="RIGHT" NUMBERFORMATEX="2">$this->getSum("VALUE")</COL>
				</ROW>
				<ROW>
					<COL COLSPAN="3" CELLCLASS="FOOTER"></COL>
				</ROW>
			</FOOTER>
			<GROUP NAME="customer" EXPRESSION="NAME" RESET_SUPPRESS_ON_PAGEBREAK="TRUE" REPRINT_HEADER_ON_PAGEBREAK="TRUE">
				<HEADER>
					<ROW>
						<COL CELLCLASS="HEADER" ALIGN="RIGHT" WIDTH="50">customer:</COL>
						<COL CELLCLASS="HEADER" TEXTCLASS="BOLD" TYPE="EXPRESSION" COLSPAN="2"><LINK TYPE="EXPRESSION" TARGET="_blank" TITLE="click here to check info about the customer">"http://localhost/getcustomerinfo.php?name=".$this->getValue("NAME")</LINK>$this->getValue("NAME")</COL>
					</ROW>
					<ROW>
						<COL CELLCLASS="HEADER" TEXTCLASS="BOLD" ALIGN="LEFT">type</COL>
						<COL CELLCLASS="HEADER" TEXTCLASS="BOLD" ALIGN="LEFT">title</COL>
						<COL CELLCLASS="HEADER" TEXTCLASS="BOLD" ALIGN="RIGHT">$</COL>
					</ROW>
				</HEADER>
				<FIELDS>
					<ROW>
						<COL TYPE="FIELD" CELLCLASSEVEN="EVEN" CELLCLASSODD="ODD" ALIGN="LEFT" SUPPRESS="TRUE">TYPE</COL>
						<COL TYPE="FIELD" CELLCLASSEVEN="EVEN" CELLCLASSODD="ODD" ALIGN="LEFT">ITEM</COL>
						<COL TYPE="FIELD" CELLCLASSEVEN="EVEN" CELLCLASSODD="ODD" ALIGN="RIGHT">VALUE</COL>
					</ROW>
				</FIELDS>
				<FOOTER>
					<ROW>
						<COL ALIGN="RIGHT" TYPE="EXPRESSION" CELLCLASS="FOOTER" COLSPAN="2">"total of ".$this->getValue("NAME")</COL>
						<COL TYPE="EXPRESSION" CELLCLASS="FOOTER" TEXTCLASS="BOLD" ALIGN="RIGHT" NUMBERFORMATEX="2">$this->getSum("VALUE")</COL>
					</ROW>
					<ROW>
						<COL COLSPAN="3" TYPE="EXPRESSION" CELLCLASS="FOOTER" TEXTCLASS="BOLD" ALIGN="RIGHT">($this->getSum("VALUE")>200?"*** Free shipping bonus!***":"Regular shipping charging")</COL>
					</ROW>
				</FOOTER>
			</GROUP>	
		</GROUP>
	</GROUPS>
</REPORT>

=== sgbarreros/inv/modules/reports/report_products_sold_total.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT NUMBERFORMATEX="2">
	<TITLE>Sales Report</TITLE>
   <BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
<!--   <CSS>phpreports.css</CSS>  -->
   <PAGE BORDER="1" SIZE="2500" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="500">
      <HEADER>
         <ROW>
            <COL COLSPAN="5" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Products sold in total by Product</COL>
         </ROW>
      </HEADER>		
      <FOOTER>
         <ROW>
            <COL ALIGN="RIGHT" COLSPAN="4" CELLCLASS="PAGE_LAYER">page total</COL>
            <COL ALIGN="LEFT" NUMBERFORMATEX="2" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD" TYPE="EXPRESSION">$this->getSum("sum_quantity")</COL>
         </ROW>
      </FOOTER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="citygroup" >

			<FIELDS>
				<ROW>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">description</COL>
					<COL TYPE="FIELD" CELLCLASS="GROUP_LAYER">sum_quantity</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>
